/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package akademia_ushtarake;

import static akademia_ushtarake.Admini.listUshtaret;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Blendi
 */
public class Ballina extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    /**
     * Creates new form Ballina
     */
    public Ballina() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRrethAplikacionit = new javax.swing.JButton();
        btnAplikoKetu = new javax.swing.JButton();
        btnRrethAkademise = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblMbyllja = new javax.swing.JLabel();
        lblMinimizimi = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtNumriIdentifikues = new javax.swing.JTextField();
        btnHyrja = new javax.swing.JButton();
        pswFjalekalimi = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(null);

        btnRrethAplikacionit.setBackground(new java.awt.Color(22, 30, 30));
        btnRrethAplikacionit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnRrethAplikacionit.setForeground(new java.awt.Color(240, 240, 240));
        btnRrethAplikacionit.setText("Rreth Aplikacionit");
        btnRrethAplikacionit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRrethAplikacionit.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnRrethAplikacionit.setIconTextGap(20);
        btnRrethAplikacionit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRrethAplikacionitMouseClicked(evt);
            }
        });
        getContentPane().add(btnRrethAplikacionit);
        btnRrethAplikacionit.setBounds(120, 770, 580, 30);

        btnAplikoKetu.setBackground(new java.awt.Color(22, 30, 30));
        btnAplikoKetu.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnAplikoKetu.setForeground(new java.awt.Color(240, 240, 240));
        btnAplikoKetu.setText("Apliko Ketu");
        btnAplikoKetu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAplikoKetu.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnAplikoKetu.setIconTextGap(20);
        btnAplikoKetu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAplikoKetuMouseClicked(evt);
            }
        });
        btnAplikoKetu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplikoKetuActionPerformed(evt);
            }
        });
        getContentPane().add(btnAplikoKetu);
        btnAplikoKetu.setBounds(120, 670, 580, 30);

        btnRrethAkademise.setBackground(new java.awt.Color(22, 30, 30));
        btnRrethAkademise.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnRrethAkademise.setForeground(new java.awt.Color(240, 240, 240));
        btnRrethAkademise.setText("Rreth Akademise");
        btnRrethAkademise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRrethAkademise.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnRrethAkademise.setIconTextGap(20);
        btnRrethAkademise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRrethAkademiseMouseClicked(evt);
            }
        });
        getContentPane().add(btnRrethAkademise);
        btnRrethAkademise.setBounds(120, 720, 580, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(55, 66, 58)));
        jPanel2.setName(""); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Akademia Ushtarake");

        lblMbyllja.setIcon(new javax.swing.ImageIcon("C:\\Users\\Blendi\\Desktop\\ICONS\\exit.png")); // NOI18N
        lblMbyllja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMbyllja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMbylljaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMbylljaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMbylljaMouseExited(evt);
            }
        });

        lblMinimizimi.setIcon(new javax.swing.ImageIcon("C:\\Users\\Blendi\\Desktop\\ICONS\\minimize.png")); // NOI18N
        lblMinimizimi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizimi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizimiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizimiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizimiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1004, Short.MAX_VALUE)
                .addComponent(lblMinimizimi)
                .addGap(18, 18, 18)
                .addComponent(lblMbyllja)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMbyllja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMinimizimi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1500, 80);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(55, 66, 58), new java.awt.Color(55, 66, 58), new java.awt.Color(55, 66, 58)))); // NOI18N
        jPanel1.setOpaque(false);

        txtNumriIdentifikues.setBackground(new java.awt.Color(255, 255, 255, 0));
        txtNumriIdentifikues.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        txtNumriIdentifikues.setForeground(new java.awt.Color(255, 255, 255));
        txtNumriIdentifikues.setMargin(new java.awt.Insets(2, 20, 2, 2));
        txtNumriIdentifikues.setOpaque(false);
        txtNumriIdentifikues.setSelectionColor(new java.awt.Color(0, 102, 102));

        btnHyrja.setBackground(new java.awt.Color(22, 30, 30));
        btnHyrja.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 25)); // NOI18N
        btnHyrja.setForeground(new java.awt.Color(255, 255, 255));
        btnHyrja.setIcon(new javax.swing.ImageIcon("C:\\Users\\Blendi\\Desktop\\hyrja.png")); // NOI18N
        btnHyrja.setText("Hyrja");
        btnHyrja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHyrja.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnHyrja.setIconTextGap(20);
        btnHyrja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHyrjaActionPerformed(evt);
            }
        });

        pswFjalekalimi.setBackground(new java.awt.Color(255, 255, 255, 0));
        pswFjalekalimi.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        pswFjalekalimi.setForeground(new java.awt.Color(255, 255, 255));
        pswFjalekalimi.setCaretColor(new java.awt.Color(240, 240, 240));
        pswFjalekalimi.setMargin(new java.awt.Insets(2, 20, 2, 2));
        pswFjalekalimi.setOpaque(false);
        pswFjalekalimi.setSelectionColor(new java.awt.Color(0, 102, 102));
        pswFjalekalimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswFjalekalimiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numri Identifikues");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fjalekalimi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHyrja, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumriIdentifikues, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswFjalekalimi, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumriIdentifikues, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswFjalekalimi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btnHyrja)
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(120, 150, 580, 510);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Blendi\\Desktop\\army1.jpg")); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -60, 1500, 900);

        setSize(new java.awt.Dimension(1499, 833));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMbylljaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMbylljaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblMbylljaMouseClicked

    private void lblMbylljaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMbylljaMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("images/exit1.png"));
        lblMbyllja.setIcon(A);
    }//GEN-LAST:event_lblMbylljaMouseEntered

    private void lblMbylljaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMbylljaMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("images/exit.png"));
        lblMbyllja.setIcon(A);
    }//GEN-LAST:event_lblMbylljaMouseExited

    private void lblMinimizimiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizimiMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizimiMouseClicked

    private void lblMinimizimiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizimiMouseEntered
       ImageIcon B = new ImageIcon(getClass().getResource("images/minimize1 .png"));
       lblMinimizimi.setIcon(B);
        
    }//GEN-LAST:event_lblMinimizimiMouseEntered

    private void lblMinimizimiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizimiMouseExited
        ImageIcon B = new ImageIcon(getClass().getResource("images/minimize.png"));
        lblMinimizimi.setIcon(B);
    }//GEN-LAST:event_lblMinimizimiMouseExited

    private void pswFjalekalimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswFjalekalimiActionPerformed
        pswFjalekalimi.setBackground(new Color(0, 0, 0, 0));
    }//GEN-LAST:event_pswFjalekalimiActionPerformed

    private void btnRrethAplikacionitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRrethAplikacionitMouseClicked
        

        //dispatchEvent(new WindowEvent(aplikimif, WindowEvent.WINDOW_CLOSED));
    }//GEN-LAST:event_btnRrethAplikacionitMouseClicked

    private void btnAplikoKetuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAplikoKetuMouseClicked
       Aplikimi aplikimif = new Aplikimi();
        aplikimif.setVisible(true);
        aplikimif.pack();
        aplikimif.setLocationRelativeTo(null);
        aplikimif.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnAplikoKetuMouseClicked

    private void btnRrethAkademiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRrethAkademiseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRrethAkademiseMouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
         yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btnHyrjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHyrjaActionPerformed
        Connection connection = null;
        Statement st;
        
        ResultSet rs = null;
        
        String id =txtNumriIdentifikues.getText();
        String password = pswFjalekalimi.getText();
        
        if( id.length()==7){
        try{
           int log=1;
           //st =(Statement)connection.createStatement();
           //rs= st.executeQuery("Select UshtariId, FjalekalimiU from Ushtaret");
            
            String SQL_LIST = "Select UshtariId, FjalekalimiU from Ushtaret";
            connection = OracleDBConfig.getConnection();
            st = connection.createStatement();
            rs = st.executeQuery(SQL_LIST);
                
           String Identifikimi=txtNumriIdentifikues.getText();
           
           while (rs.next())
           {
               if(rs.getString(1).equals(id) && rs.getString(2).equals(password))
               {
                   log = 0;
                   break;
               }
           }
           if(log==0){
                this.dispose();
                Ushtari A= new Ushtari();
                A.setVisible(true);
                //A.setAlwaysOnTop(true);
           }
         
        }
        catch(SQLException sql_ex){
            sql_ex.printStackTrace();
        }
        }
        else if(id.length()==6){
            try{
           int log=1;
           //st =(Statement)connection.createStatement();
           //rs= st.executeQuery("Select UshtariId, FjalekalimiU from Ushtaret");
            
            String SQL_LIST = "Select TogeriId, FjalekalimiT from Togeret";
            connection = OracleDBConfig.getConnection();
            st = connection.createStatement();
            rs = st.executeQuery(SQL_LIST);
             
           
           
           String Identifikimi=txtNumriIdentifikues.getText();
           
           while (rs.next())
           {
               if(rs.getString(1).equals(id) && rs.getString(2).equals(password))
               {
                   log = 0;
                   break;
               }
           }
           if(log==0){
                this.dispose();
                Togeri A= new Togeri();
                A.setVisible(true);
                //A.setAlwaysOnTop(true);
           }
           
                
            
            
            
            
        }
        catch(SQLException sql_ex){
            sql_ex.printStackTrace();
        }
        }
        else if(id.equals("Admin")){
              try{
           int log=1;
           //st =(Statement)connection.createStatement();
           //rs= st.executeQuery("Select UshtariId, FjalekalimiU from Ushtaret");
            
            String SQL_LIST = "Select FjalekalimiA from Adminet";
            connection = OracleDBConfig.getConnection();
            st = connection.createStatement();
            rs = st.executeQuery(SQL_LIST);
             
           
           
           String Identifikimi=txtNumriIdentifikues.getText();
           
           while (rs.next())
           {
               if(rs.getString(1).equals(password))
               {
                   log = 0;
                   break;
               }
           }
           if(log==0){
                this.dispose();
                Admini A= new Admini();
                A.setVisible(true);
                //A.setAlwaysOnTop(true);
           }
           
                
            
            
            
            
        }
        catch(SQLException sql_ex){
            sql_ex.printStackTrace();
        }
        } 
       
            
        
        

        
    }//GEN-LAST:event_btnHyrjaActionPerformed

    private void btnAplikoKetuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplikoKetuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAplikoKetuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ballina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ballina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ballina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ballina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ballina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplikoKetu;
    private javax.swing.JButton btnHyrja;
    private javax.swing.JButton btnRrethAkademise;
    private javax.swing.JButton btnRrethAplikacionit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMbyllja;
    private javax.swing.JLabel lblMinimizimi;
    private javax.swing.JPasswordField pswFjalekalimi;
    public static javax.swing.JTextField txtNumriIdentifikues;
    // End of variables declaration//GEN-END:variables
}
