/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package akademia_ushtarake;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Blendi
 */
public class Togeri extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();
    /**
     * Creates new form Togeri
     */
    public Togeri() {
        initComponents();
        this.setSize(screen.width, screen.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPozita = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblEmri = new javax.swing.JLabel();
        lblMbiemri = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPostimi = new javax.swing.JButton();
        lblNjofto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNjofto = new javax.swing.JTextArea();
        btnDil = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblMbyllja = new javax.swing.JLabel();
        lblMinimizimi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Emri dhe Mbiemri :");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 740, 210, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Numri Identifikues :");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 550, 210, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pozita :");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 150, 210, 40);

        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 530, 360, 10);

        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 720, 360, 10);

        jLabel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(""), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 120, 400, 920);

        lblPozita.setFont(new java.awt.Font("Times New Roman", 0, 35)); // NOI18N
        lblPozita.setForeground(new java.awt.Color(255, 255, 255));
        lblPozita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPozita.setText("asd");
        lblPozita.setToolTipText("");
        getContentPane().add(lblPozita);
        lblPozita.setBounds(120, 420, 220, 50);

        lblId.setFont(new java.awt.Font("Times New Roman", 0, 35)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblId.setText("asd");
        lblId.setToolTipText("");
        getContentPane().add(lblId);
        lblId.setBounds(120, 620, 220, 50);

        lblEmri.setFont(new java.awt.Font("Times New Roman", 0, 35)); // NOI18N
        lblEmri.setForeground(new java.awt.Color(255, 255, 255));
        lblEmri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmri.setText("jLabel5");
        lblEmri.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblEmriAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(lblEmri);
        lblEmri.setBounds(50, 830, 190, 40);

        lblMbiemri.setFont(new java.awt.Font("Times New Roman", 0, 35)); // NOI18N
        lblMbiemri.setForeground(new java.awt.Color(255, 255, 255));
        lblMbiemri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMbiemri.setText("asd");
        lblMbiemri.setToolTipText("");
        getContentPane().add(lblMbiemri);
        lblMbiemri.setBounds(230, 890, 160, 50);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(""), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        btnPostimi.setBackground(new java.awt.Color(51, 51, 51));
        btnPostimi.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnPostimi.setForeground(new java.awt.Color(240, 240, 240));
        btnPostimi.setText("Posto");
        btnPostimi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPostimi.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnPostimi.setIconTextGap(20);
        btnPostimi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPostimiMouseClicked(evt);
            }
        });
        btnPostimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostimiActionPerformed(evt);
            }
        });
        jPanel1.add(btnPostimi);
        btnPostimi.setBounds(120, 760, 370, 50);

        lblNjofto.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        lblNjofto.setForeground(new java.awt.Color(255, 255, 255));
        lblNjofto.setText("Njofto");
        jPanel1.add(lblNjofto);
        lblNjofto.setBounds(120, 140, 195, 38);

        txtNjofto.setBackground(new java.awt.Color(153, 153, 153));
        txtNjofto.setBackground(new java.awt.Color(255, 255, 255,0));
        txtNjofto.setColumns(20);
        txtNjofto.setRows(5);
        jScrollPane1.setViewportView(txtNjofto);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 180, 370, 560);

        btnDil.setBackground(new java.awt.Color(51, 51, 51));
        btnDil.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnDil.setForeground(new java.awt.Color(240, 240, 240));
        btnDil.setText("Dil");
        btnDil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDil.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnDil.setIconTextGap(20);
        btnDil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDilMouseClicked(evt);
            }
        });
        btnDil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDilActionPerformed(evt);
            }
        });
        jPanel1.add(btnDil);
        btnDil.setBounds(1290, 10, 150, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(430, 120, 1450, 920);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setName(""); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Miresevini");

        lblMbyllja.setIcon(new javax.swing.ImageIcon("C:\\Users\\Blendi\\Desktop\\ICONS\\exit.png")); // NOI18N
        lblMbyllja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMbyllja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMbylljaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMbylljaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMbylljaMouseExited(evt);
            }
        });

        lblMinimizimi.setIcon(new javax.swing.ImageIcon("C:\\Users\\Blendi\\Desktop\\ICONS\\minimize.png")); // NOI18N
        lblMinimizimi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizimi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizimiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizimiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizimiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1417, Short.MAX_VALUE)
                .addComponent(lblMinimizimi)
                .addGap(18, 18, 18)
                .addComponent(lblMbyllja)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMbyllja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMinimizimi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-10, -10, 1950, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Blendi\\Desktop\\dark.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1960, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMbylljaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMbylljaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblMbylljaMouseClicked

    private void lblMbylljaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMbylljaMouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("images/exit1.png"));
        lblMbyllja.setIcon(A);
    }//GEN-LAST:event_lblMbylljaMouseEntered

    private void lblMbylljaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMbylljaMouseExited
        ImageIcon A = new ImageIcon(getClass().getResource("images/exit.png"));
        lblMbyllja.setIcon(A);
    }//GEN-LAST:event_lblMbylljaMouseExited

    private void lblMinimizimiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizimiMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizimiMouseClicked

    private void lblMinimizimiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizimiMouseEntered
        ImageIcon B = new ImageIcon(getClass().getResource("images/minimize1 .png"));
        lblMinimizimi.setIcon(B);
    }//GEN-LAST:event_lblMinimizimiMouseEntered

    private void lblMinimizimiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizimiMouseExited
        ImageIcon B = new ImageIcon(getClass().getResource("images/minimize.png"));
        lblMinimizimi.setIcon(B);
    }//GEN-LAST:event_lblMinimizimiMouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void lblEmriAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblEmriAncestorAdded
        try{
            Connection connection = null;
            Statement stmt = null;
            ResultSet rs = null;

            String sql="select * from Togeret where TogeriId=100000";

            connection = OracleDBConfig.getConnection();
            stmt = connection.createStatement();
            rs = stmt.executeQuery(sql);
            while(rs.next())
            {
                lblEmri.setText(rs.getString("EmriT"));
                lblMbiemri.setText(rs.getString("MbiemriT"));
                lblPozita.setText(rs.getString("PozitaT"));
                lblId.setText(rs.getString("TogeriId"));

            }

        }
        catch(Exception e ){

        }
    }//GEN-LAST:event_lblEmriAncestorAdded

    private void btnPostimiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPostimiMouseClicked
        
    }//GEN-LAST:event_btnPostimiMouseClicked

    private void btnPostimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostimiActionPerformed
       try{
            Connection connection = null;
            Statement stmt = null;
            ResultSet rs = null;

            String sql="insert into Postimet (TogeriId, Postimi) values (100000,'"+txtNjofto.getText().toString()+"')";

            connection = OracleDBConfig.getConnection();
            stmt = connection.createStatement();
            rs = stmt.executeQuery(sql);
            
            JOptionPane.showMessageDialog(this,"Postimi u krye me sukses");
            txtNjofto.setText("");

        }
        catch(SQLException sql_ex){
            sql_ex.printStackTrace();

        }
    }//GEN-LAST:event_btnPostimiActionPerformed

    private void btnDilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDilMouseClicked

    private void btnDilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDilActionPerformed
        this.dispose();
        Ballina A= new Ballina();
        A.setVisible(true);
    }//GEN-LAST:event_btnDilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Togeri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Togeri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Togeri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Togeri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Togeri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDil;
    private javax.swing.JButton btnPostimi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmri;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMbiemri;
    private javax.swing.JLabel lblMbyllja;
    private javax.swing.JLabel lblMinimizimi;
    private javax.swing.JLabel lblNjofto;
    private javax.swing.JLabel lblPozita;
    private javax.swing.JTextArea txtNjofto;
    // End of variables declaration//GEN-END:variables
}
